from __future__ import print_function
import sys
import random
import json


def randDoc(id):
    x = []
    y = []
    texto = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus hendrerit, diam id convallis tempor, lacus sem egestas lacus, vitae feugiat nibh tortor eu urna. Nulla sit amet imperdiet nulla, et auctor ante. Pellentesque ac molestie eros. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent aliquam malesuada eros sed vulputate. Suspendisse rhoncus tortor velit, sit amet hendrerit lorem ultrices vel. Sed nec enim volutpat, porttitor tortor sed, interdum justo. Donec vel neque leo. In a aliquam nisl. Fusce vestibulum convallis tortor finibus aliquam. Cras accumsan, eros ac mollis elementum, purus sapien tincidunt tortor, id placerat odio justo quis magna. Proin posuere tristique mauris. Integer dictum elementum rutrum. Sed eleifend lectus ante, a finibus eros efficitur eu. Suspendisse potenti." \
            "Aliquam a velit laoreet, vestibulum erat in, aliquet risus. Aenean ac consequat purus, nec rhoncus velit. Duis sollicitudin, sapien in accumsan iaculis, urna leo bibendum erat, ut vehicula lorem nulla a mauris. Suspendisse maximus suscipit nisi at varius. Quisque pellentesque dolor ac leo malesuada, quis euismod arcu ornare. Donec nec pulvinar arcu. Donec dapibus ipsum purus, vel ornare eros ullamcorper sit amet. Aliquam erat volutpat. Cras sit amet libero magna. Morbi cursus dui massa, eget porta purus euismod aliquet. Suspendisse potenti. Fusce dignissim lacus sit amet fringilla consequat. Morbi in neque ullamcorper, placerat sem in, sagittis lectus. Nullam feugiat tempus gravida. Proin sagittis turpis at blandit bibendum." \
            "Pellentesque varius finibus vehicula. Duis diam justo, tempus id felis vitae, bibendum vehicula leo. Nulla dictum consectetur elit non interdum. Nunc eleifend ipsum vel convallis bibendum. Pellentesque vulputate tortor lacus, consectetur elementum metus facilisis a. Fusce gravida consequat sem, sit amet venenatis dui egestas quis. Curabitur consequat, sapien vel tempor convallis, nisi purus tristique diam, in consequat sem lorem vel metus." \
            "In porttitor condimentum lobortis. Mauris interdum iaculis viverra. Quisque non purus neque. Nulla aliquet commodo orci, vitae ultrices mi dapibus non. Aliquam eleifend magna tortor, id laoreet est vehicula eu. Suspendisse egestas ligula quis nisl vestibulum semper. Quisque quis hendrerit nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque faucibus felis vel pharetra laoreet. Maecenas vel ullamcorper justo. Cras sagittis non nisl vel dignissim.Vivamus accumsan urna quis dolor aliquam luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam ac turpis ac risus gravida posuere. Curabitur egestas condimentum laoreet. Quisque in purus in sem ornare luctus. Nulla facilisi. Morbi semper sit amet urna eu bibendum.Integer hendrerit ut tortor sed pellentesque. Sed pulvinar id ipsum vitae tincidunt. Cras tempor mollis leo, et finibus magna consectetur ac. Curabitur laoreet sit amet massa eget aliquam. Etiam egestas nibh non orci pulvinar, non pharetra ex venenatis. Aliquam a ornare sapien, sed porttitor dolor. Curabitur vitae risus libero.Duis pretium nibh vel augue mollis, quis molestie arcu tristique. Vivamus id lacus sodales, facilisis lacus at, condimentum libero. Ut laoreet volutpat metus quis semper. Fusce ut quam a nibh aliquet gravida non nec odio. Integer feugiat diam at varius accumsan. Mauris pharetra orci sit amet leo condimentum commodo. Ut blandit, nisi at imperdiet congue, nibh ipsum auctor nibh, eu iaculis felis risus nec ante. Morbi eget laoreet nunc. Suspendisse et pharetra orci, sit amet maximus libero. Donec nunc nulla, mattis a bibendum ac, iaculis porttitor odio. Phasellus molestie tempor iaculis. Curabitur at purus eget dolor pharetra iaculis ac at arcu. Nulla id odio suscipit, commodo sapien ac, semper ligula. Duis pulvinar massa nec eros pulvinar, id euismod erat interdum. Sed dictum ex quis dui sodales, eget ullamcorper sapien vestibulum. Maecenas ac dignissim turpis, quis pharetra velit.Nullam id purus et erat sagittis eleifend. Nam a elit sit amet dolor tristique mattis id ut magna. Donec lobortis leo sed purus accumsan gravida. Duis dignissim libero nibh, auctor egestas diam dapibus ac. Curabitur dapibus, purus et dictum dictum, turpis lorem accumsan orci, lacinia vulputate ipsum lectus tincidunt nisl. Aenean tempus augue a est volutpat convallis. Morbi iaculis velit nec dolor sollicitudin, sit amet vestibulum leo euismod. Ut rutrum quam et augue ullamcorper dapibus." \
            "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed fringilla nisi suscipit leo rutrum, vitae vehicula mauris convallis. Integer mollis cursus velit, nec dapibus dui faucibus in. Fusce ut tellus sed tellus lacinia rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec enim ligula, dapibus quis semper at, faucibus a libero. Nam in tellus rutrum, laoreet arcu ut, condimentum nisl. Donec ac finibus ex, eu tristique neque. Nulla imperdiet, lorem nec iaculis volutpat, nisl nibh vehicula lorem, vel venenatis nulla nisl nec tellus. Duis venenatis lacus quis ullamcorper pretium. Etiam placerat vestibulum laoreet. Maecenas sodales ultrices quam et pretium. Aenean in quam at urna egestas ullamcorper id feugiat eros. Quisque ligula mauris, laoreet non nibh ac, condimentum vulputate odio. Integer tincidunt elit non tempor porttitor. Nam non efficitur felis, quis accumsan purus." \
            "In hac habitasse platea dictumst. Mauris non velit at tortor fringilla tristique sit amet ut purus. Cras auctor libero risus, a sagittis neque rutrum finibus. In aliquam orci ut odio finibus, nec vestibulum leo lobortis. In hac habitasse platea dictumst. Phasellus ac nunc pellentesque, volutpat dui quis, posuere dui. Curabitur dapibus egestas dolor, id tristique massa convallis vitae. In dapibus, lacus quis vulputate consequat, turpis sapien interdum ex, non iaculis enim dolor in nisl.Ut tincdunt purus ac nisl aliquet, fringilla luctus libero rutrum. Vivamus et scelerisque velit. Ut urna leo, semper non ex in, rutrum sollicitudin orci. Praesent blandit, mi quis tempus mollis, dolor sapien porta felis, eu sollicitudin enim urna quis orci. Nam vitae tortor libero. Phasellus convallis turpis ac justo pulvinar, sed dictum risus hendrerit. Donec pharetra est eget velit lacinia porta. Sed volutpat odio vehicula eros vehicula efficitur.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum metus id arcu auctor efficitur. Ut vehicula sit amet dui sed maximus. Morbi hendrerit euismod nisi, vitae commodo nisl accumsan in. Praesent sed ultrices magna. Sed tempus efficitur eleifend. Suspendisse potenti. Sed vitae mauris id quam dictum commodo non et eros. Nullam sed mauris neque. Nunc sit amet nunc urna. Vivamus viverra aliquam gravida. Integer eu nisl in lectus malesuada pharetra. Nunc neque est, porttitor ut arcu id, vehicula tincidunt nunc. Nunc odio mauris, pharetra sit amet lacinia sit amet, auctor ut massa.Quisque lobortis enim eu mi maximus scelerisque. Curabitur pretium lorem id nisl iaculis, quis convallis magna suscipit. Suspendisse fringilla cursus nisi, eget blandit ligula venenatis eget. Aliquam porta tristique elit eget congue. Aliquam sodales tellus non turpis luctus elementum ac sed ipsum. Curabitur pulvinar vestibulum iaculis. Phasellus quis elementum ligula. Duis neque ex, vestibulum nec rhoncus iaculis, laoreet nec lacus. Maecenas sit amet condimentum ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.Vivamus ornare ac ante at pretium. Morbi fermentum, velit ut porta viverra, leo mauris ultrices massa, sed ullamcorper leo magna ac lectus. Nulla in leo libero. Sed tempor faucibus metus, sed elementum ligula scelerisque quis. In turpis dui, aliquet at ligula nec, feugiat auctor est. Fusce sodales elementum scelerisque. Nulla finibus nisi nisl, ac consequat sapien mattis sed. Proin fermentum maximus commodo. Suspendisse potenti. Donec vel ipsum quis orci rhoncus venenatis eu vel tortor. Phasellus id turpis vitae nibh blandit condimentum." \
            "Quisque in lectus a felis fringilla dapibus. Nunc convallis sem id est dignissim placerat. Cras vel odio nibh. Nam cursus elit ac ex hendrerit, sit amet imperdiet massa mollis. Nulla consectetur ante eu erat suscipit porttitor. Quisque vulputate pulvinar viverra. Duis odio orci, iaculis quis vulputate euismod, sagittis in purus. Sed aliquam aliquam eros, eget semper nulla laoreet eget. Phasellus non purus non orci rhoncus scelerisque. Vestibulum volutpat efficitur varius. Cras ullamcorper at orci quis semper. Integer nec bibendum augue. Suspendisse ut arcu ante. In auctor ligula non suscipit varius. Aenean vel ligula nec metus facilisis varius imperdiet quis lectus." \
            "Nunc vulputate lectus at orci facilisis mattis. Aenean ut nulla eget lacus laoreet vestibulum. Praesent imperdiet ut mauris venenatis ultrices. Nulla ante diam, facilisis quis ex id, rutrum aliquam sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce laoreet velit id urna accumsan ullamcorper. Phasellus laoreet dui eget nisl ullamcorper vestibulum." \
            "Pellentsque pulvinar enim eget nisi condimentum feugiat. Vivamus laoreet interdum posuere. Praesent convallis tortor rhoncus diam cursus, nec facilisis dui posuere. Nullam eu consequat metus. Pellentesque nisl nulla, finibus in bibendum eget, luctus sed felis. Aliquam in volutpat magna, a iaculis velit. Pellentesque tempus magna a tincidunt ullamcorper. Aliquam a elit velit.Mauris a ex vitae dolor venenatis ultrices. Nunc dapibus ante commodo maximus dapibus. Suspendisse luctus fermentum efficitur. Nam sed magna vel odio pulvinar commodo. Suspendisse lacinia lectus eget dui auctor, nec lobortis magna luctus. Proin vulputate vehicula semper. Morbi sit amet sodales velit, id malesuada leo. Aenean elementum magna non justo hendrerit porta. Aenean et ante eu augue tristique blandit. Nullam massa leo, malesuada vel condimentum nullam."
    post = {"_id": id, "x": x, "y": y, "texto": texto}

    x.append(random.uniform(0.0, 2.0))
    x.append(random.uniform(2.0, 6.0))
    x.append(random.uniform(6.0, 8.0))
    x.append(random.uniform(8.0, 10.0))

    y.append(random.uniform(0.0, 1.5))
    y.append(random.uniform(1.5, 3.0))
    y.append(random.uniform(3.0, 7.0))
    y.append(random.uniform(7.0, 15.0))

    post["x"]
    post["y"]
    post["texto"]
    return post


for i in xrange(500000000):
    doc = randDoc(i)
    print(json.dumps(doc))
    if i % 1000 == 0:
        print(".", end="", file=sys.stderr)

# Para pasar a json y poblar la bd

# python m50.py > m50.json
"siteRootAdmin", "password"
# mongoimport --db admin --collection datas100 --username siteRootAdmin --password password -v --drop  --file m100.json
# mongoimport --db system --collection js -v   --file fuzzy.json
# db.mycoll.stats()
